package com.sk.batch.delete.api.model;

import java.util.HashSet;
import java.util.List;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@Setter
@Getter
@DynamoDBTable(tableName = "Customer")
public class Customer {

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  @DynamoDBAttribute
  private String id;

  @DynamoDBIndexHashKey(globalSecondaryIndexName = "Customer_client_id")
  @DynamoDBAttribute(attributeName = "client_id")
  private String clientId;
  @DynamoDBAttribute
  private String name;


  @DynamoDBAttribute
  private String type;


  @DynamoDBAttribute(attributeName = "client_secret")
  private String clientSecret;


  @DynamoDBAttribute(attributeName = "trusted_application_ids")
  private HashSet<String> trustedApplicationIds;


  @DynamoDBAttribute(attributeName = "authorization_providers")
  private HashSet<String> authorizationProviders;


  @DynamoDBAttribute(attributeName = "authentication_providers")
  private HashSet<String> authenticationProviders;


  @DynamoDBAttribute(attributeName = "redirect_uris")
  private HashSet<String> redirectUris;


  @DynamoDBAttribute(attributeName = "policy_name")
  private String policyName;


  @DynamoDBAttribute(attributeName = "ciam_provider_id")
  private String ciamProviderId;


  @DynamoDBAttribute(attributeName = "template_id")
  private String templateId;


  @DynamoDBAttribute(attributeName = "application_team_dl")
  private String applicationTeamdl;


  @DynamoDBAttribute(attributeName = "comments")
  private String comments;


  @DynamoDBAttribute(attributeName = "created_by")
  private String createdBy;


  @DynamoDBAttribute(attributeName = "updated_by")
  private String updatedBy;


  @DynamoDBAttribute(attributeName = "created")
  private long created;


  @DynamoDBAttribute(attributeName = "updated")
  private long updated;


  @DynamoDBAttribute(attributeName = "state")
  private String state;


  @DynamoDBAttribute(attributeName = "validation_ciam_provider_id")
  private String validationCiamProviderId;


  @DynamoDBAttribute(attributeName = "parent_id")
  private String parentId;




}
