package com.sk.batch.delete.api.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Setter
@Getter
@NoArgsConstructor
@DynamoDBTable(tableName = "deleteAudit")
public class DeleteAudit {

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  public String id;
  @DynamoDBHashKey(attributeName = "sqs_message_id")
  public String sqsMessageId;
  @DynamoDBHashKey(attributeName = "requestApiPath")
  public String request_api_path;
  @DynamoDBHashKey(attributeName = "request_params")
  public String requestParams;
  @DynamoDBHashKey(attributeName = "delete_category")
  public String deleteCategory;
  @DynamoDBHashKey(attributeName = "delete_description")
  public String deleteDescription;
  @DynamoDBHashKey(attributeName = "requested_time")
  public long requestedTime;
  @DynamoDBHashKey(attributeName = "delete_table_id")
  @DynamoDBIndexHashKey(globalSecondaryIndexName = "delete_id_index")
  public String deleteTableId;
  @DynamoDBHashKey(attributeName = "status")
  public String status;
  @DynamoDBHashKey(attributeName = "created_by")
  public String createdBy;
  @DynamoDBHashKey(attributeName = "created")
  public long created;
  @DynamoDBHashKey(attributeName = "updated_by")
  public String updatedBy;
  @DynamoDBHashKey(attributeName = "updated")
  public long updated;
  @DynamoDBHashKey(attributeName = "process_count")
  public long processCount;
  @DynamoDBHashKey(attributeName = "error_description")
  public String errorDescription;

}
